### ISSUE TITLE
Python 3.4 on travis

### ISSUE THREAD

**Issue by DasIch** [DasIch/argvard#6]
Travis doesn't have Python 3.4 installed. Can we install it?

**Comment by untitaker** [comment]
This could probably work: https://launchpad.net/~fkrull/+archive/deadsnakes

**Comment by untitaker** [comment]
In order to use custom PPAs for Python versions, you'd probably have to stop relying on Travis' python versions completely and use that PPA + envvars. Not sure if that's worth it, compared to the alternative of waiting for Travis to officially pick up 3.4

**Comment by untitaker** [comment]
Oh jesus christ, you already do that.

**Comment by DasIch** [comment]
Fixed by d81e4fdeae87f94e2c9d0b4aa88d354a570a1bea

**Comment by DasIch** [comment]
Indeed :D I actually forgot that it's that simple.
